// Maps: Professional Title → Services/Specialties for that title
export const servicesByTitle: Record<string, string[]> = {
  // Digital Marketing titles
  'Digital Marketer': ['Social Media Management', 'Content Strategy', 'Analytics & Reporting', 'Campaign Management'],
  'Social Media Manager': ['Social Media Management', 'Content Creation', 'Community Management', 'Influencer Outreach'],
  'Content Strategist': ['Content Strategy', 'Content Creation', 'SEO Optimization', 'Editorial Planning'],
  'SEO Specialist': ['SEO Optimization', 'Keyword Research', 'Technical SEO', 'Link Building'],
  'PPC Specialist': ['PPC Management', 'Ad Copy Writing', 'Landing Page Optimization', 'Campaign Optimization'],
  'Email Marketing Manager': ['Email Campaign Management', 'List Building', 'Automation Setup', 'A/B Testing'],
  'Marketing Automation Specialist': ['Automation Setup', 'Workflow Design', 'Integration Services', 'Performance Tracking'],
  'Digital Analyst': ['Analytics & Reporting', 'Data Analysis', 'Competitive Analysis', 'Performance Metrics'],
  'Growth Manager': ['Growth Strategy', 'User Acquisition', 'Conversion Optimization', 'Product Development'],
  'Brand Manager': ['Brand Strategy', 'Brand Guidelines', 'Market Research', 'Brand Positioning'],

  // Brand Ambassador titles
  'Brand Ambassador': ['Event Representation', 'Social Media Promotion', 'Product Sampling', 'Community Engagement'],
  'Community Manager': ['Community Management', 'Engagement Strategy', 'Moderation', 'Content Curation'],
  'Brand Advocate': ['Brand Advocacy', 'Product Promotion', 'Testimonials & Reviews', 'Network Building'],
  'Influencer': ['Social Media Content', 'Product Endorsement', 'Sponsored Posts', 'Campaign Participation'],
  'Brand Representative': ['Brand Liaison', 'Customer Relations', 'Feedback Collection', 'Relationship Management'],
  'Engagement Specialist': ['Engagement Strategy', 'Event Coordination', 'Audience Management', 'Feedback Analysis'],

  // Media Communications titles
  'Communications Manager': ['Communications Strategy', 'Press Release Writing', 'Media Relations', 'Crisis Management'],
  'Public Relations Specialist': ['Media Relations', 'Press Release Writing', 'Event Promotion', 'Brand Reputation'],
  'Media Coordinator': ['Media Coordination', 'Press Kit Preparation', 'Media Outreach', 'Scheduling'],
  'Press Officer': ['Press Releases', 'Media Briefings', 'Media Relations', 'Statement Preparation'],
  'Communications Specialist': ['Internal Communications', 'External Communications', 'Messaging Strategy', 'Content Distribution'],
  'Copywriter': ['Copywriting', 'Ad Copy', 'Website Copy', 'Blog Posts'],

  // Media Production titles
  'Producer': ['Production Management', 'Budget Management', 'Crew Coordination', 'Post-Production Supervision'],
  'Videographer': ['Video Filming', 'Live Streaming', 'Video Editing', 'Motion Graphics'],
  'Director': ['Creative Direction', 'Shot Composition', 'Actor Direction', 'Post-Production Oversight'],
  'Cinematographer': ['Cinematography', 'Lighting Design', 'Camera Operation', 'Color Grading'],
  'Video Editor': ['Video Editing', 'Motion Graphics', 'Color Correction', 'Audio Mixing'],
  'Production Assistant': ['Production Support', 'Equipment Management', 'Scheduling', 'Documentation'],
  'Broadcast Technician': ['Broadcast Management', 'Technical Setup', 'Live Production', 'Equipment Maintenance'],

  // Art & Design titles
  'Graphic Designer': ['Logo Design', 'Print Design', 'Digital Design', 'Brand Identity'],
  'UI/UX Designer': ['UI Design', 'UX Research', 'Wireframing', 'Prototyping'],
  'Illustrator': ['Illustration', 'Character Design', 'Icon Design', 'Digital Painting'],
  'Art Director': ['Creative Direction', 'Visual Concept Development', 'Art Supervision', 'Design Strategy'],
  'Motion Designer': ['Motion Graphics', 'Animation', 'Visual Effects', 'Kinetic Typography'],
  'Visual Designer': ['Visual Design', 'Layout Design', 'Color Theory Application', 'Typography Design'],

  // Modelling titles
  'Model': ['Fashion Modeling', 'Commercial Modeling', 'Print Modeling', 'Portfolio Building'],
  'Runway Model': ['Runway Shows', 'Fashion Presentations', 'Event Appearances', 'Fashion Week'],
  'Commercial Model': ['Commercial Shoots', 'TV Commercials', 'Advertising', 'Brand Representation'],
  'Fashion Model': ['Fashion Shoots', 'Lookbook Creation', 'Editorial Modeling', 'Campaign Modeling'],
  'Print Model': ['Print Modeling', 'Magazine Features', 'Catalog Shoots', 'Product Photography'],
  'Promotional Model': ['Event Promotion', 'Trade Show Appearances', 'Promotional Engagement', 'Brand Activation'],

  // Dance & Choreography titles
  'Dancer': ['Live Performance', 'Choreography Interpretation', 'Concert Performances', 'Video Dance'],
  'Choreographer': ['Choreography Creation', 'Dance Direction', 'Concept Development', 'Movement Training'],
  'Dance Instructor': ['Dance Classes', 'Private Lessons', 'Group Training', 'Online Instruction'],
  'Dance Director': ['Dance Direction', 'Creative Supervision', 'Performer Coordination', 'Production Oversight'],
  'Backup Dancer': ['Live Performance', 'Concert Backup', 'Music Video Appearance', 'Event Performance'],
  'Contemporary Dancer': ['Contemporary Performance', 'Improvisation', 'Experimental Movement', 'Artistic Interpretation'],

  // Acting titles
  'Actor': ['Film Acting', 'Theater Acting', 'Television Acting', 'Voice Acting'],
  'Actress': ['Film Acting', 'Theater Acting', 'Television Acting', 'Commercial Acting'],
  'Voice Actor': ['Voice Recording', 'Character Voicing', 'Narration', 'Audio Drama'],
  'Character Actor': ['Character Development', 'Supporting Roles', 'Specialized Acting', 'Method Acting'],
  'Stunt Performer': ['Stunt Coordination', 'Action Scenes', 'Dangerous Stunts', 'Safety Management'],
  'Stage Actor': ['Theater Performance', 'Live Acting', 'Stage Presence', 'Improvisation'],

  // Film & Video Production titles
  'Filmmaker': ['Film Direction', 'Production Management', 'Post-Production', 'Creative Oversight'],
  'Film Producer': ['Production Planning', 'Budget Management', 'Crew Management', 'Post-Production'],
  'Video Producer': ['Video Production', 'Project Management', 'Quality Control', 'Delivery Management'],
  'Film Director': ['Directorial Services', 'Creative Vision', 'Production Supervision', 'Creative Direction'],
  'Video Coordinator': ['Production Coordination', 'Scheduling', 'Equipment Management', 'Documentation'],

  // Audio Production titles
  'Audio Engineer': ['Audio Recording', 'Mixing', 'Mastering', 'Audio Restoration'],
  'Sound Designer': ['Sound Design', 'Audio Effects', 'Ambient Design', 'Sonic Branding'],
  'Mixing Engineer': ['Audio Mixing', 'Level Balancing', 'Effects Processing', 'Quality Assurance'],
  'Mastering Engineer': ['Audio Mastering', 'Final Optimization', 'Format Conversion', 'Distribution Prep'],
  'Voice Over Artist': ['Voice Recording', 'Narration', 'Character Voices', 'Localization'],
  'Sound Technician': ['Sound Setup', 'Technical Support', 'Equipment Maintenance', 'Live Sound'],
  'Recording Engineer': ['Audio Recording', 'Session Management', 'Technical Setup', 'Quality Control'],

  // Music titles
  'Musician': ['Live Performance', 'Session Playing', 'Music Composition', 'Recording'],
  'Singer': ['Live Singing', 'Studio Recording', 'Vocal Performance', 'Feature Vocals'],
  'Composer': ['Music Composition', 'Arrangement', 'Orchestration', 'Soundtrack Creation'],
  'Music Producer': ['Music Production', 'Beat Production', 'Song Production', 'Album Production'],
  'Songwriter': ['Songwriting', 'Lyric Writing', 'Composition', 'Music Publishing'],
  'Instrumentalist': ['Instrument Performance', 'Session Recording', 'Live Accompaniment', 'Studio Playing'],
  'Music Arranger': ['Music Arrangement', 'Orchestration', 'Adaptation', 'Instrumentation'],

  // Event Management titles
  'Event Manager': ['Event Planning', 'Logistics Management', 'Vendor Coordination', 'On-site Management'],
  'Event Coordinator': ['Event Coordination', 'Timeline Management', 'Vendor Liaison', 'Execution Support'],
  'Event Planner': ['Full Event Planning', 'Conceptualization', 'Budget Planning', 'Implementation'],
  'Venue Manager': ['Venue Coordination', 'Space Management', 'Technical Support', 'Facility Management'],
  'Event Producer': ['Event Production', 'Creative Concept', 'Technical Execution', 'Quality Assurance'],
  'Logistics Coordinator': ['Logistics Planning', 'Supply Management', 'Timeline Coordination', 'Delivery'],

  // Photography titles
  'Photographer': ['Photography', 'Photo Editing', 'Retouching', 'Image Curation'],
  'Portrait Photographer': ['Portrait Photography', 'Headshots', 'Family Photography', 'Personal Branding'],
  'Commercial Photographer': ['Commercial Photography', 'Product Photography', 'Corporate Photography', 'Advertising'],
  'Photo Editor': ['Photo Editing', 'Color Correction', 'Retouching', 'Batch Processing'],
  'Studio Photographer': ['Studio Photography', 'Lighting Setup', 'Studio Sessions', 'Backdrop Setup'],
  'Fashion Photographer': ['Fashion Photography', 'Lookbook Photography', 'Editorial Photography', 'Campaign Photography'],
  'Event Photographer': ['Event Photography', 'Coverage', 'Live Photography', 'Event Documentation'],

  // Design titles
  'Designer': ['Graphic Design', 'Brand Design', 'Layout Design', 'Visual Design'],
  'Graphic Designer': ['Logo Design', 'Print Design', 'Digital Design', 'Brand Identity'],
  'UI/UX Designer': ['UI Design', 'UX Research', 'Wireframing', 'Prototyping'],
  'Product Designer': ['Product Design', 'Design Research', 'Prototyping', 'User Testing'],
  'Web Designer': ['Web Design', 'Responsive Design', 'UX Design', 'Interface Design'],
  'Industrial Designer': ['Product Design', 'Concept Development', 'Manufacturing Design', '3D Modeling'],
  'Design Consultant': ['Design Consulting', 'Design Strategy', 'Design Audit', 'Custom Solutions'],
  'Design Specialist': ['Graphic Design', 'Digital Design', 'Brand Design', 'Design Strategy'],
};

// Maps: Service/Specialty → Specific Service Menu items (priceable types)
export const serviceMenuByService: Record<string, string[]> = {
  'Social Media Management': ['Instagram Management', 'Facebook Management', 'TikTok Management', 'LinkedIn Management'],
  'Content Strategy': ['Content Planning', 'Content Calendar', 'Keyword Strategy', 'Audience Research'],
  'Analytics & Reporting': ['Monthly Analytics Report', 'Quarterly Report', 'Custom Dashboard', 'Competitive Analysis'],
  'Campaign Management': ['Campaign Setup', 'Campaign Monitoring', 'A/B Testing', 'Campaign Optimization'],
  'Content Creation': ['Blog Posts', 'Social Posts', 'Video Scripts', 'Graphic Content'],
  'Community Management': ['Community Moderation', 'Member Engagement', 'Response Management', 'Community Growth'],
  'Influencer Outreach': ['Influencer Database', 'Outreach Campaign', 'Partnership Management', 'Collaboration Setup'],
  'SEO Optimization': ['On-page SEO', 'Technical SEO', 'Local SEO', 'International SEO'],
  'Keyword Research': ['Keyword Analysis', 'Competitor Keywords', 'Long-tail Keywords', 'Keyword Mapping'],
  'Technical SEO': ['Site Audit', 'Speed Optimization', 'Mobile Optimization', 'Schema Markup'],
  'Link Building': ['Backlink Analysis', 'Link Outreach', 'Guest Posting', 'Directory Submission'],
  'PPC Management': ['Google Ads Management', 'Facebook Ads Management', 'LinkedIn Ads Management', 'Retargeting'],
  'Ad Copy Writing': ['Google Ads Copy', 'Facebook Ad Copy', 'Landing Page Copy', 'Banner Copy'],
  'Landing Page Optimization': ['Landing Page Design', 'Conversion Optimization', 'A/B Testing', 'Load Speed Optimization'],
  'Campaign Optimization': ['Performance Tuning', 'Budget Optimization', 'Bid Management', 'Quality Improvement'],
  'Email Campaign Management': ['Email Design', 'List Segmentation', 'Campaign Scheduling', 'Template Creation'],
  'List Building': ['Lead Generation', 'List Cleaning', 'Database Building', 'Subscriber Growth'],
  'Automation Setup': ['Workflow Automation', 'Trigger Setup', 'Email Sequences', 'Lead Nurturing'],
  'A/B Testing': ['Subject Line Testing', 'Content Testing', 'Send Time Optimization', 'Template Testing'],
  'Workflow Design': ['Process Mapping', 'Automation Workflow', 'Integration Setup', 'Testing'],
  'Integration Services': ['Platform Integration', 'API Setup', 'Data Synchronization', 'Custom Integration'],
  'Performance Tracking': ['KPI Monitoring', 'Dashboard Creation', 'Reporting', 'Analysis'],
  'Data Analysis': ['Statistical Analysis', 'Trend Analysis', 'Forecasting', 'Insights Generation'],
  'Competitive Analysis': ['Competitor Benchmarking', 'Market Analysis', 'Strategy Assessment', 'Report'],
  'Performance Metrics': ['Metric Definition', 'Tracking Setup', 'Dashboard', 'Analysis'],
  'Growth Strategy': ['Growth Planning', 'Experiment Design', 'Channel Strategy', 'Scaling'],
  'User Acquisition': ['Acquisition Strategy', 'Channel Optimization', 'Testing', 'Scaling'],
  'Conversion Optimization': ['Funnel Analysis', 'CRO Strategy', 'Testing', 'Implementation'],
  'Product Development': ['Product Strategy', 'Feature Planning', 'Roadmap', 'MVP Definition'],
  'Brand Strategy': ['Brand Positioning', 'Brand Architecture', 'Messaging Framework', 'Strategy Document'],
  'Brand Guidelines': ['Style Guide Creation', 'Logo Guidelines', 'Color Palette', 'Typography Rules'],
  'Market Research': ['Consumer Research', 'Market Analysis', 'Trend Research', 'Competitor Research'],
  'Brand Positioning': ['Positioning Strategy', 'Differentiation', 'Messaging', 'Competitive Analysis'],
  'Event Representation': ['Trade Show Presence', 'Event Activation', 'Product Launch', 'Corporate Event'],
  'Social Media Promotion': ['Post Creation', 'Story Creation', 'Reel Creation', 'Campaign Posts'],
  'Product Sampling': ['Sample Distribution', 'Demo Setup', 'Customer Engagement', 'Feedback Collection'],
  'Community Engagement': ['Community Events', 'Local Activation', 'Online Engagement', 'Relationship Building'],
  'Engagement Strategy': ['Strategy Development', 'Content Planning', 'Campaign Planning', 'Measurement Framework'],
  'Moderation': ['Comment Moderation', 'Community Monitoring', 'Issue Resolution', 'Reporting'],
  'Content Curation': ['Content Selection', 'Content Scheduling', 'Comment Responses', 'Trend Monitoring'],
  'Brand Advocacy': ['Testimonial Recording', 'Review Writing', 'Case Study', 'Success Stories'],
  'Product Promotion': ['Social Posts', 'Stories', 'Reels', 'Live Streams'],
  'Testimonials & Reviews': ['Review Writing', 'Video Testimonials', 'Case Studies', 'Success Stories'],
  'Network Building': ['Relationship Development', 'Partnership Building', 'Community Development', 'Network Expansion'],
  'Product Endorsement': ['Endorsement Content', 'Product Review', 'Usage Content', 'Promotion'],
  'Sponsored Posts': ['Instagram Sponsored', 'TikTok Sponsored', 'Facebook Sponsored', 'Multi-platform'],
  'Campaign Participation': ['Campaign Content', 'Challenge Participation', 'Campaign Posts', 'Engagement'],
  'Brand Liaison': ['Brand Connection', 'Feedback Bridge', 'Community Link', 'Relationship Management'],
  'Customer Relations': ['Customer Support', 'Feedback Collection', 'Issue Resolution', 'Satisfaction'],
  'Feedback Collection': ['Survey', 'Interview', 'Focus Group', 'Feedback Analysis'],
  'Communications Strategy': ['Strategy Document', 'Messaging Framework', 'Stakeholder Map', 'Plan'],
  'Press Release Writing': ['Press Release', 'Media Advisory', 'Statement', 'News Announcement'],
  'Media Relations': ['Media Outreach', 'Press Kit Distribution', 'Journalist Relations', 'Coverage Monitoring'],
  'Crisis Management': ['Crisis Response', 'Statement Preparation', 'Message Testing', 'Recovery Strategy'],
  'Event Promotion': ['Event Press Release', 'Media Kit', 'Interview Setup', 'Coverage Planning'],
  'Brand Reputation': ['Reputation Monitoring', 'Positive Content', 'Damage Control', 'Recovery'],
  'Press Kit Preparation': ['Press Kit Design', 'Fact Sheets', 'Bio Creation', 'Media Materials'],
  'Media Outreach': ['Media List', 'Pitch Creation', 'Email Outreach', 'Follow-up'],
  'Scheduling': ['Interview Scheduling', 'Media Meeting Setup', 'Calendar Management', 'Coordination'],
  'Press Releases': ['Standard Release', 'Feature Announcement', 'News Release', 'Media Release'],
  'Media Briefings': ['Background Briefing', 'Q&A Preparation', 'Spokesperson Training', 'Media Event'],
  'Statement Preparation': ['Official Statement', 'Quote Preparation', 'Response Statement', 'Crisis Statement'],
  'Internal Communications': ['Internal Newsletter', 'Team Updates', 'Memo', 'Internal Campaign'],
  'External Communications': ['Press Release', 'Social Posts', 'Email Campaign', 'Website Copy'],
  'Messaging Strategy': ['Core Messages', 'Talking Points', 'Key Messages', 'Brand Voice'],
  'Content Distribution': ['Multi-channel Distribution', 'Press Distribution', 'Social Distribution', 'Email Distribution'],
  'Copywriting': ['Web Copy', 'Marketing Copy', 'Email Copy', 'Social Copy'],
  'Ad Copy': ['Google Ads', 'Facebook Ads', 'Banner Ads', 'Search Ads'],
  'Website Copy': ['Homepage Copy', 'Service Pages', 'About Copy', 'Product Copy'],
  'Blog Posts': ['Blog Article', 'Thought Leadership', 'Industry Insight', 'How-to Guide'],
  'Production Management': ['Pre-production', 'Production Supervision', 'Post-production', 'Final Delivery'],
  'Budget Management': ['Budget Planning', 'Cost Control', 'Financial Reporting', 'Resource Allocation'],
  'Crew Coordination': ['Crew Scheduling', 'Role Assignment', 'Communication', 'Coordination'],
  'Post-Production Supervision': ['Post-production Planning', 'Edit Supervision', 'Quality Control', 'Final Approval'],
  'Video Filming': ['Event Filming', 'Studio Filming', 'Location Filming', 'Multi-camera Filming'],
  'Live Streaming': ['Setup and Streaming', 'Technical Management', 'Live Moderation', 'Multi-platform Streaming'],
  'Video Editing': ['Basic Editing', 'Advanced Editing', 'Color Correction', 'Sound Design'],
  'Motion Graphics': ['Animated Graphics', 'Title Sequences', 'Logo Animation', 'Lower Thirds'],
  'Creative Direction': ['Creative Concept', 'Visual Direction', 'Style Development', 'Brand Integration'],
  'Shot Composition': ['Framing', 'Lighting Setup', 'Angle Selection', 'Visual Composition'],
  'Actor Direction': ['Scene Direction', 'Performance Coaching', 'Take Management', 'Feedback'],
  'Post-Production Oversight': ['Edit Review', 'Color Grade Approval', 'Sound Approval', 'Final QC'],
  'Cinematography': ['Principle Cinematography', 'Multi-day Shoot', 'Complex Lighting', 'Complex Shots'],
  'Lighting Design': ['Studio Lighting', 'Location Lighting', 'Special Lighting', 'Mood Lighting'],
  'Camera Operation': ['Camera Setup', 'Technical Operation', 'Movement Control', 'Equipment Management'],
  'Color Grading': ['Color Correction', 'Look Development', 'Style Grading', 'Final Color'],
  'Production Support': ['Set Support', 'Equipment Support', 'Logistics Support', 'General Support'],
  'Equipment Management': ['Equipment Rental', 'Setup', 'Maintenance', 'Returns'],
  'Documentation': ['Behind-the-scenes', 'Call Sheet', 'Production Notes', 'Documentation'],
  'Broadcast Management': ['Broadcast Setup', 'Live Broadcast', 'Technical Management', 'Contingency Planning'],
  'Technical Setup': ['Studio Setup', 'Equipment Setup', 'Cable Management', 'Test'],
  'Live Production': ['Live Event', 'Live Broadcast', 'Real-time Management', 'Technical Operation'],
  'Equipment Maintenance': ['Regular Maintenance', 'Repair Service', 'Cleaning', 'Calibration'],
  'Logo Design': ['Logo Concept', 'Logo Refinement', 'Final Logo', 'Brand Identity Package'],
  'Print Design': ['Brochure Design', 'Flyer Design', 'Business Card Design', 'Poster Design'],
  'Digital Design': ['Web Design', 'App Design', 'Email Design', 'Banner Design'],
  'Brand Identity': ['Logo', 'Color Palette', 'Typography', 'Style Guide'],
  'UI Design': ['Wireframes', 'Mock-ups', 'High-fidelity Design', 'Component Design'],
  'UX Research': ['User Research', 'Usability Testing', 'User Journey', 'Competitive Analysis'],
  'Wireframing': ['Low-fidelity Wireframes', 'User Flow', 'Information Architecture', 'Interaction Design'],
  'Prototyping': ['Interactive Prototype', 'Clickable Mock-up', 'Animation Prototype', 'User Testing'],
  'Illustration': ['Custom Illustration', 'Editorial Illustration', 'Commercial Illustration', 'Digital Painting'],
  'Character Design': ['Character Concept', 'Character Modeling', 'Character Sheet', 'Animation Ready'],
  'Icon Design': ['Icon Set', 'Custom Icons', 'Icon System', 'Scalable Icons'],
  'Digital Painting': ['Digital Art', 'Painting', 'Digital Illustration', 'Creative Work'],
  'Visual Concept Development': ['Concept Sketches', 'Concept Boards', 'Visual Direction', 'Style Development'],
  'Art Supervision': ['Creative Review', 'Direction Approval', 'Quality Control', 'Final Approval'],
  'Design Strategy': ['Design Direction', 'Design Framework', 'Design Roadmap', 'Strategic Plan'],
  'Animation': ['Character Animation', 'Motion Animation', 'Stop-motion', 'Complex Animation'],
  'Visual Effects': ['Special Effects', 'VFX Integration', 'Complex Effects', 'Advanced VFX'],
  'Kinetic Typography': ['Text Animation', 'Dynamic Text', 'Moving Text', 'Animated Type'],
  'Layout Design': ['Page Layout', 'Grid System', 'Information Design', 'Visual Hierarchy'],
  'Color Theory Application': ['Color Palette', 'Color Harmony', 'Color Psychology', 'Brand Colors'],
  'Typography Design': ['Font Selection', 'Font Pairing', 'Type Hierarchy', 'Custom Typography'],
  'Fashion Modeling': ['Fashion Show', 'Catalog Shoot', 'Fashion Campaign', 'Lookbook'],
  'Commercial Modeling': ['Commercial Shoot', 'TV Commercial', 'Print Ad', 'Product Modeling'],
  'Print Modeling': ['Magazine Feature', 'Catalog Work', 'Editorial', 'Product Photography'],
  'Magazine Features': ['Magazine Feature', 'Editorial Shoot', 'Magazine Photography', 'Lifestyle Editorial'],
  'Catalog Shoots': ['Catalog Work', 'Product Photography', 'Fashion Catalog', 'Multiple Looks'],
  'Editorial Planning': ['Content Planning', 'Editorial Calendar', 'Story Development', 'Publication Strategy'],
  'Social Media Content': ['Post Creation', 'Story Creation', 'Reel Creation', 'Campaign Posts'],
  'Voice Recording': ['Character Voice', 'Narration', 'Localization', 'Audio Drama'],
  'Character Voices': ['Character Voice Performance', 'Multi-character Voices', 'Voice Consistency', 'Localization'],
  'Localization': ['Localization', 'Language Adaptation', 'Cultural Adjustment', 'Regional Adaptation'],
  'Delivery Management': ['Project Delivery', 'Quality Assurance', 'Timeline Adherence', 'Final Handoff'],
  'Project Management': ['Project Planning', 'Schedule Management', 'Resource Allocation', 'Stakeholder Communication'],
  'Audio Mixing': ['Audio Mixing', 'Stereo Mixing', '5.1 Mixing', 'Surround Mixing'],
  'Experimentation': ['A/B Testing', 'Growth Testing', 'Channel Testing', 'Implementation Testing'],
  'Artist Management': ['Artist Representation', 'Contract Negotiation', 'Career Development', 'Partnership Building'],
  'Contract Negotiation': ['Deal Terms', 'Contract Review', 'Legal Support', 'Negotiation'],
  'Career Development': ['Career Planning', 'Skill Development', 'Professional Growth', 'Mentorship'],
  'Talent Booking': ['Talent Scheduling', 'Event Booking', 'Campaign Booking', 'Project Assignment'],
  'Partnership Development': ['Partnership Building', 'Collaboration Setup', 'Joint Ventures', 'Strategic Alliances'],
  'Journalist Relations': ['Media Pitching', 'Press Release Distribution', 'Journalist Database', 'Coverage Building'],
  'Coverage Monitoring': ['Media Monitoring', 'Coverage Tracking', 'Sentiment Analysis', 'Impact Reporting'],
  'Brand Voice': ['Voice Development', 'Tone Guidelines', 'Messaging Consistency', 'Brand Communication'],
  'Location Coordination': ['Location Scouting', 'Permits & Permissions', 'Local Logistics', 'Site Management'],
  'Live Broadcasting': ['Broadcast Setup', 'Live Stream Management', 'Technical Operation', 'Broadcast Monitoring'],
  'Equipment Setup': ['Equipment Installation', 'Technical Configuration', 'Cable Management', 'System Testing'],
  'Technical Support': ['Technical Assistance', 'Troubleshooting', 'On-site Support', 'Issue Resolution'],
  'Motion Design': ['Motion Graphics', 'Animation', 'Visual Effects', 'Kinetic Typography'],
  'Graphic Design': ['Logo Design', 'Print Design', 'Digital Design', 'Brand Design'],
  'App Design': ['UI Design', 'UX Design', 'Wireframing', 'Prototyping'],
  'Interactive Design': ['Interactive Prototype', 'Animation Design', 'User Interaction', 'Behavior Design'],
  'Design Consultation': ['Design Review', 'Design Strategy', 'Design Audit', 'Custom Solutions'],
  'Casting Management': ['Casting Services', 'Audition Coordination', 'Talent Selection', 'Booking Management'],
  'Talent Development': ['Talent Training', 'Portfolio Building', 'Career Coaching', 'Professional Development'],
  'Booking Management': ['Booking Scheduling', 'Contract Management', 'Event Coordination', 'Client Communication'],
  'Casting Services': ['Casting Auditions', 'Talent Selection', 'Role Matching', 'Contract Negotiation'],
  'Talent Database': ['Talent Roster', 'Database Management', 'Skill Inventory', 'Quick Access'],
  'Audition Coordination': ['Audition Scheduling', 'Audition Logistics', 'Feedback Collection', 'Results Management'],
  'Performance Production': ['Performance Planning', 'Rehearsal Coordination', 'Technical Production', 'Quality Assurance'],
  'Rehearsal Coordination': ['Schedule Management', 'Venue Booking', 'Equipment Setup', 'Performer Coordination'],
  'Performer Coordination': ['Schedule Management', 'Communication', 'Role Assignment', 'Performance Support'],
  'Touring': ['Tour Planning', 'Venue Booking', 'Logistics Coordination', 'Schedule Management'],
  'Acting Classes': ['Beginner Classes', 'Advanced Training', 'Private Coaching', 'Workshop Sessions'],
  'Private Coaching': ['One-on-one Training', 'Personalized Development', 'Technique Coaching', 'Performance Feedback'],
  'Direction Services': ['Directorial Consultation', 'Scene Direction', 'Performance Direction', 'Creative Vision'],
  'Post-Production Management': ['Edit Supervision', 'Color Grade Review', 'Sound Design Management', 'Quality Control'],
  'Digital Content Creation': ['Video Production', 'Animation', 'Motion Graphics', 'Visual Effects'],
  'Creative Control': ['Creative Direction', 'Artistic Vision', 'Design Oversight', 'Final Approval'],
  'Distribution Support': ['Distribution Strategy', 'Platform Submission', 'Rights Management', 'Launch Support'],
  'Technical Services': ['Technical Setup', 'Equipment Rental', 'Technical Support', 'Problem Solving'],
  'Equipment Rental': ['Equipment Checkout', 'Maintenance', 'Return Management', 'Delivery Service'],
  'Audio Production': ['Audio Recording', 'Mixing', 'Mastering', 'Sound Design'],
  'Music Production': ['Beat Production', 'Song Production', 'Album Production', 'Audio Recording'],
  'Mastering Engineer': ['Audio Mastering', 'Format Mastering', 'Distribution Prep', 'Quality Assurance'],
  'Final Optimization': ['Final Audio Polish', 'Quality Enhancement', 'Format Optimization', 'Distribution Ready'],
  'Technical Consulting': ['Technical Audit', 'Strategy Development', 'Solution Design', 'Implementation Support'],
  'Artist Promotion': ['Promotional Campaign', 'Media Outreach', 'Social Media Promotion', 'Event Promotion'],
  'Royalty Management': ['Royalty Tracking', 'Payment Processing', 'Rights Management', 'Financial Reporting'],
  'A&R Services': ['Artist Scouting', 'Talent Evaluation', 'Production Coordination', 'Release Strategy'],
  'Rights Management': ['Rights Negotiation', 'License Management', 'Copyright Protection', 'Contract Management'],
  'Licensing': ['License Negotiation', 'Usage Rights', 'Royalty Agreements', 'Legal Documentation'],
  'Catalog Management': ['Catalog Organization', 'Metadata Input', 'Rights Documentation', 'Asset Management'],
  'Conference Organization': ['Event Planning', 'Venue Selection', 'Vendor Coordination', 'Logistics Management'],
  'Registration Management': ['Registration Setup', 'Attendee Tracking', 'Check-in Management', 'Data Collection'],
  'Technical Execution': ['Technical Setup', 'Live Management', 'Quality Assurance', 'Problem Resolution'],
  'Photographer Booking': ['Booking Scheduling', 'Event Coordination', 'Rate Negotiation', 'Contract Management'],
  'Photography Services': ['Photography Booking', 'Editing Services', 'Delivery Management', 'Client Support'],
  'Event Coverage': ['Event Photography', 'Full Day Coverage', 'Multiple Events', 'Photo Delivery'],
  'Advertising Photography': ['Product Ads', 'Commercial Photography', 'Campaign Photography', 'Professional Shoot'],
  'E-commerce Photography': ['Product Photography', 'Lifestyle Shots', 'Multiple Angles', 'Professional Shoot'],
  'Image Enhancement': ['Photo Editing', 'Color Correction', 'Retouching', 'Effect Application'],
  'Photography': ['Photography Service', 'Photo Delivery', 'Editing Included', 'Archive Management'],
  'Graphics': ['Graphic Design', 'Illustration', 'Icon Design', 'Visual Assets'],
  'Web Design': ['Website Design', 'Responsive Design', 'UX Design', 'Front-end Design'],
  'Interactive Experience': ['Interactive Installation', 'Experiential Design', 'Engagement Activity', 'Brand Activation'],
  'Implementation': ['Plan Implementation', 'Execution', 'Deployment', 'Launch'],
  'Portfolio Building': ['Portfolio Shoot', 'Comp Cards', 'Digital Portfolio', 'Professional Photos'],
  'Runway Shows': ['Fashion Week', 'Designer Show', 'Charity Runway', 'Commercial Runway'],
  'Fashion Presentations': ['Fashion Presentation', 'Collection Preview', 'Brand Show', 'Launch Event'],
  'Event Appearances': ['Brand Event', 'Product Launch', 'Red Carpet', 'Promotional Event'],
  'Fashion Week': ['Fashion Week Show', 'Multiple Shows', 'Collections', 'Designer Collaboration'],
  'TV Commercials': ['Commercial Filming', 'On-camera Acting', 'Product Feature', 'Branded Content'],
  'Advertising': ['Print Ads', 'Digital Ads', 'Billboard', 'Campaign Ads'],
  'Commercial Shoots': ['Commercial Photography', 'Product Photography', 'Brand Photography', 'Professional Shoot'],
  'Fashion Shoots': ['Fashion Photography', 'Editorial Shoot', 'Campaign Photography', 'Designer Shoot'],
  'Lookbook Creation': ['Lookbook Photography', 'Lookbook Styling', 'Lookbook Design', 'Complete Lookbook'],
  'Editorial Modeling': ['Magazine Feature', 'Editorial Photography', 'Luxury Brand', 'High Fashion'],
  'Campaign Modeling': ['Campaign Photography', 'Brand Campaign', 'Multiple Day Shoot', 'Campaign Package'],
  'Trade Show Appearances': ['Trade Show Booth', 'Brand Representation', 'Interactive Booth', 'Networking'],
  'Promotional Engagement': ['Event Appearance', 'Brand Activation', 'Interactive Experience', 'Experiential Marketing'],
  'Brand Activation': ['Brand Event', 'Interactive Experience', 'Brand Engagement', 'Experiential Marketing'],
  'Live Performance': ['Concert Performance', 'Theater Performance', 'Event Performance', 'Festival Performance'],
  'Choreography Interpretation': ['Choreography Performance', 'Artist Interpretation', 'Concept Execution', 'Creative Performance'],
  'Concert Performances': ['Tour Performance', 'Concert Appearance', 'Multi-show Tour', 'Festival Performance'],
  'Video Dance': ['Music Video', 'Online Content', 'Promotional Video', 'Digital Content'],
  'Choreography Creation': ['Custom Choreography', 'Concept Development', 'Full Production', 'Artistic Direction'],
  'Dance Direction': ['Rehearsal Direction', 'Performance Direction', 'Artistic Supervision', 'Creative Direction'],
  'Concept Development': ['Creative Concept', 'Artistic Vision', 'Theme Development', 'Narrative Development'],
  'Movement Training': ['Dance Training', 'Technique Training', 'Movement Coaching', 'Performance Coaching'],
  'Dance Classes': ['Group Classes', 'Class Series', 'Weekly Classes', 'Semester Classes'],
  'Private Lessons': ['One-on-one Lesson', 'Intensive Training', 'Personalized Coaching', 'Custom Training'],
  'Group Training': ['Small Group Class', 'Workshop', 'Intensive Workshop', 'Masterclass'],
  'Online Instruction': ['Virtual Classes', 'Online Lessons', 'Recorded Lessons', 'Streaming Classes'],
  'Performer Coordination': ['Performer Management', 'Rehearsal Coordination', 'Schedule Management', 'Team Direction'],
  'Production Oversight': ['Technical Oversight', 'Quality Control', 'Final Approval', 'Production Management'],
  'Improvisation': ['Improvisation Performance', 'Spontaneous Creativity', 'Real-time Performance', 'Freestyle'],
  'Experimental Movement': ['Contemporary Movement', 'Avant-garde', 'Experimental Forms', 'Innovative Movement'],
  'Artistic Interpretation': ['Creative Interpretation', 'Unique Performance', 'Artistic Vision', 'Creative Expression'],
  'Film Acting': ['Feature Film', 'Short Film', 'Independent Film', 'Commercial Film'],
  'Theater Acting': ['Stage Performance', 'Theater Production', 'Live Theater', 'Theater Run'],
  'Television Acting': ['TV Series', 'TV Movie', 'Commercial', 'Guest Appearance'],
  'Voice Acting': ['Character Voice', 'Narration', 'Animation Voice', 'Game Voice'],
  'Character Voicing': ['Character Voice Performance', 'Multi-character Voices', 'Voice Consistency', 'Character Development'],
  'Narration': ['Documentary Narration', 'Audiobook Narration', 'Corporate Narration', 'Promotional Narration'],
  'Audio Drama': ['Audio Drama Performance', 'Radio Drama', 'Podcast Acting', 'Audio Series'],
  'Character Development': ['Character Study', 'Character Coaching', 'Method Acting', 'Character Depth'],
  'Supporting Roles': ['Supporting Actor', 'Co-lead', 'Guest Role', 'Character Role'],
  'Specialized Acting': ['Stunt Acting', 'Dialect Acting', 'Action Scenes', 'Specialized Performance'],
  'Method Acting': ['Deep Character Work', 'Method Technique', 'Emotional Performance', 'Immersive Acting'],
  'Stunt Coordination': ['Action Coordination', 'Stunt Planning', 'Safety Management', 'Action Direction'],
  'Action Scenes': ['Action Choreography', 'Fight Scenes', 'Chase Scenes', 'Complex Action'],
  'Dangerous Stunts': ['High-risk Stunts', 'Specialized Stunts', 'Complex Sequences', 'Professional Stunt Work'],
  'Safety Management': ['Safety Planning', 'Risk Assessment', 'Safety Protocols', 'Emergency Procedures'],
  'Stage Performance': ['Live Performance', 'Theater Acting', 'Live Event', 'Stage Acting'],
  'Stage Presence': ['Performance Presence', 'Stage Command', 'Audience Engagement', 'Dramatic Presence'],
  'Commercial Acting': ['Commercial Audition', 'Commercial Performance', 'Product Acting', 'Brand Acting'],
  'Film Direction': ['Feature Direction', 'Short Direction', 'Commercial Direction', 'Music Video Direction'],
  'Production Planning': ['Scheduling', 'Budget Planning', 'Resource Planning', 'Logistics Planning'],
  'Crew Management': ['Crew Hiring', 'Team Coordination', 'Role Assignment', 'Communication'],
  'Budget Planning': ['Budget Development', 'Cost Estimation', 'Financial Planning', 'Resource Allocation'],
  'Cost Control': ['Expense Management', 'Budget Monitoring', 'Cost Reduction', 'Financial Reporting'],
  'Financial Reporting': ['Budget Report', 'Expense Report', 'Financial Analysis', 'Cost Summary'],
  'Scene Direction': ['Scene Blocking', 'Performance Direction', 'Camera Direction', 'Action Direction'],
  'Visual Storytelling': ['Visual Narrative', 'Cinematic Vision', 'Story Visualization', 'Artistic Expression'],
  'Directorial Services': ['Full Direction Service', 'Creative Vision', 'Production Execution', 'Final Vision'],
  'Creative Vision': ['Concept Development', 'Artistic Direction', 'Visual Style', 'Brand Integration'],
  'Production Coordination': ['Coordination', 'Timeline Management', 'Logistics Support', 'Execution'],
  'Audio Recording': ['Studio Recording', 'Live Recording', 'Multi-track Recording', 'Vocal Recording'],
  'Mixing': ['Audio Mixing', 'Stereo Mixing', '5.1 Mixing', 'Surround Mixing'],
  'Mastering': ['Audio Mastering', 'Format Mastering', 'Streaming Mastering', 'Vinyl Mastering'],
  'Audio Restoration': ['Noise Removal', 'Clicking Removal', 'Declicking', 'Audio Cleanup'],
  'Sound Design': ['Sound Design', 'Audio Effects', 'Ambient Sound', 'Soundscape'],
  'Audio Effects': ['Effect Processing', 'Special Effects', 'Audio Enhancement', 'Creative Effects'],
  'Ambient Design': ['Ambient Sound', 'Background Audio', 'Environmental Sound', 'Atmospheric Design'],
  'Sonic Branding': ['Audio Logo', 'Brand Sound', 'Sonic Identity', 'Audio Signature'],
  'Level Balancing': ['Volume Mixing', 'Level Optimization', 'Dynamic Range', 'Audio Balance'],
  'Effects Processing': ['Effect Application', 'Effect Chains', 'Creative Processing', 'Sound Shaping'],
  'Quality Assurance': ['Audio QC', 'Testing', 'Listening Check', 'Technical Review'],
  'Format Conversion': ['Format Conversion', 'Codec Conversion', 'Sample Rate Conversion', 'Bit Depth Conversion'],
  'Distribution Prep': ['Distribution Package', 'Metadata Input', 'File Preparation', 'Delivery Files'],
  'Session Management': ['Session Planning', 'Musician Coordination', 'Session Recording', 'Documentation'],
  'Quality Control': ['Audio Testing', 'QC Check', 'Listening Review', 'Final Check'],
  'Session Playing': ['Session Recording', 'Session Performance', 'Instrument Recording', 'Session Musician'],
  'Music Composition': ['Original Composition', 'Custom Music', 'Score Composition', 'Theme Composition'],
  'Recording': ['Studio Recording', 'Vocal Recording', 'Instrument Recording', 'Track Recording'],
  'Live Singing': ['Concert Singing', 'Live Performance', 'Public Performance', 'Event Singing'],
  'Studio Recording': ['Vocal Recording', 'Demo Recording', 'Album Recording', 'Track Recording'],
  'Vocal Performance': ['Live Vocals', 'Vocal Performance', 'Solo Performance', 'Group Performance'],
  'Feature Vocals': ['Feature Vocals', 'Guest Vocals', 'Collaboration Vocals', 'Featured Artist'],
  'Arrangement': ['Music Arrangement', 'Score Arrangement', 'Orchestration', 'Instrumentation'],
  'Orchestration': ['Orchestral Arrangement', 'Full Orchestration', 'String Arrangement', 'Complete Orchestration'],
  'Soundtrack Creation': ['Soundtrack Composition', 'Score Composition', 'Theme Music', 'Background Music'],
  'Beat Production': ['Beat Creation', 'Instrumental Beats', 'Backing Tracks', 'Rhythm Production'],
  'Song Production': ['Full Song Production', 'Track Production', 'Album Track', 'Single Production'],
  'Album Production': ['Full Album Production', 'Album Management', 'Multi-track Production', 'Complete Album'],
  'Lyric Writing': ['Original Lyrics', 'Songwriting', 'Lyric Development', 'Song Concept'],
  'Music Publishing': ['Publishing Setup', 'Rights Management', 'Royalty Management', 'Distribution'],
  'Instrument Performance': ['Instrument Solo', 'Ensemble Performance', 'Backing Instrument', 'Live Instrument'],
  'Live Accompaniment': ['Piano Accompaniment', 'Guitar Accompaniment', 'Ensemble Accompaniment', 'Live Back-up'],
  'Studio Playing': ['Studio Session', 'Instrument Recording', 'Session Musician', 'Track Recording'],
  'Music Arrangement': ['Arrangement Service', 'Orchestral Arrangement', 'Custom Arrangement', 'Full Arrangement'],
  'Adaptation': ['Adaptation Service', 'Style Adaptation', 'Format Adaptation', 'Custom Adaptation'],
  'Instrumentation': ['Instrument Selection', 'Orchestration', 'Instrumentation Design', 'Instrument Combination'],
  'Event Planning': ['Full Event Planning', 'Venue Selection', 'Vendor Coordination', 'Complete Planning'],
  'Logistics Management': ['Logistics Planning', 'Supply Management', 'Timeline Management', 'Coordination'],
  'Vendor Coordination': ['Vendor Selection', 'Vendor Management', 'Contract Negotiation', 'Coordination'],
  'On-site Management': ['Day-of Coordination', 'On-site Management', 'Timeline Execution', 'Problem Solving'],
  'Event Coordination': ['Event Coordination', 'Day-of Coordination', 'Logistics Support', 'Execution'],
  'Timeline Management': ['Schedule Development', 'Timeline Creation', 'Schedule Adherence', 'Execution'],
  'Vendor Liaison': ['Vendor Communication', 'Vendor Management', 'Coordination', 'Issue Resolution'],
  'Execution Support': ['Day-of Support', 'Setup Support', 'Coordination Support', 'Teardown Support'],
  'Full Event Planning': ['Complete Planning', 'Concept to Execution', 'Full Service', 'End-to-End'],
  'Conceptualization': ['Concept Development', 'Event Concept', 'Theme Development', 'Creative Direction'],
  'Implementation': ['Event Execution', 'Plan Implementation', 'Day-of Execution', 'Setup and Operation'],
  'Space Management': ['Venue Coordination', 'Space Planning', 'Setup Management', 'Capacity Planning'],
  'Facility Management': ['Facility Operations', 'Maintenance', 'Utilities', 'Parking and Access'],
  'Logistics Planning': ['Supply Planning', 'Transportation', 'Equipment Planning', 'Resource Allocation'],
  'Supply Management': ['Equipment Rental', 'Supply Ordering', 'Inventory Management', 'Distribution'],
  'Delivery': ['On-time Delivery', 'Logistics Delivery', 'Transportation', 'Timely Delivery'],
  'Relationship Development': ['Vendor Relationships', 'Client Relationships', 'Network Building', 'Partnership'],
  'Partnership Building': ['Strategic Partnerships', 'Collaboration', 'Joint Ventures', 'Mutual Benefit'],
  'Community Development': ['Community Building', 'Network Expansion', 'Relationship Growth', 'Community Engagement'],
  'Network Expansion': ['Network Growth', 'Relationship Expansion', 'Connection Building', 'Opportunity Development'],
  'Photography': ['Portrait Photography', 'Event Photography', 'Commercial Photography', 'Product Photography'],
  'Photo Editing': ['Basic Editing', 'Advanced Editing', 'Batch Editing', 'Color Correction'],
  'Retouching': ['Skin Retouching', 'Object Removal', 'Detailed Retouching', 'Creative Retouching'],
  'Image Curation': ['Photo Selection', 'Image Organization', 'Portfolio Curation', 'Final Selection'],
  'Portrait Photography': ['Professional Headshot', 'Actor Headshots', 'Headshot Session', 'Multiple Options'],
  'Family Photography': ['Family Session', 'Extended Family', 'Lifestyle Photos', 'Family Portraits'],
  'Personal Branding': ['Personal Brand Photos', 'LinkedIn Headshots', 'Brand Photos', 'Professional Images'],
  'Commercial Photography': ['Commercial Photography', 'Product Photography', 'Corporate Photography', 'Advertising'],
  'Product Photography': ['Product Shoot', 'Commercial Product', 'E-commerce Photography', 'Product Catalog'],
  'Corporate Photography': ['Corporate Events', 'Corporate Portraits', 'Workplace Photography', 'Corporate Content'],
  'Studio Photography': ['Studio Session', 'In-studio Shooting', 'Controlled Lighting', 'Studio Portraits'],
  'Lighting Setup': ['Professional Lighting', 'Light Design', 'Studio Lighting', 'Technical Lighting'],
  'Studio Sessions': ['Studio Booking', 'Scheduled Session', 'Dedicated Session', 'Studio Time'],
  'Backdrop Setup': ['Background Selection', 'Backdrop Installation', 'Custom Backdrops', 'Set Design'],
  'Lookbook Photography': ['Lookbook Session', 'Multiple Looks', 'Fashion Photography', 'Lookbook Package'],
  'Editorial Photography': ['Editorial Shoot', 'Magazine Photography', 'Lifestyle Editorial', 'Creative Editorial'],
  'Campaign Photography': ['Campaign Shoot', 'Brand Campaign', 'Multiple Day Shoot', 'Campaign Package'],
  'Event Photography': ['Full Event Coverage', 'Multiple Hours', 'Complete Documentation', 'Event Package'],
  'Coverage': ['Event Coverage', 'Documentation Coverage', 'Full Coverage', 'Complete Coverage'],
  'Live Photography': ['Real-time Photography', 'Candid Photography', 'Spontaneous Shots', 'Moment Capture'],
  'Event Documentation': ['Event Photos', 'Documentation', 'Archive Photos', 'Complete Coverage'],
  'Color Correction': ['Color Correction', 'White Balance', 'Tone Adjustment', 'Creative Color'],
  'Batch Processing': ['Bulk Editing', 'Consistent Edits', 'Multiple Image Editing', 'Batch Processing'],
  'Graphic Design': ['Logo Design', 'Print Design', 'Digital Design', 'Brand Design'],
  'Brand Design': ['Brand Identity', 'Logo Design', 'Brand Guidelines', 'Complete Branding'],
  'Visual Design': ['Web Visual Design', 'UI Visual Design', 'Creative Design', 'Visual Elements'],
  'Responsive Design': ['Mobile Design', 'Tablet Design', 'Desktop Design', 'Multi-device Design'],
  'Interface Design': ['User Interface', 'Interactive Design', 'Digital Interface', 'App Interface'],
  'Design Research': ['User Research', 'Market Research', 'Competitive Analysis', 'Insights'],
  'User Testing': ['Usability Testing', 'User Feedback', 'Testing Sessions', 'Validation'],
  'Manufacturing Design': ['Product Manufacturing', 'Technical Design', 'CAD Design', 'Production Specification'],
  '3D Modeling': ['3D Model', '3D Rendering', '3D Visualization', '3D Product Design'],
  'Design Consulting': ['Design Consulting', 'Design Strategy', 'Design Audit', 'Custom Solutions'],
  'Custom Solutions': ['Bespoke Design', 'Custom Design', 'Tailored Solution', 'Unique Design'],
  'Design Audit': ['Design Review', 'Usability Audit', 'Brand Audit', 'Analysis Report'],
};

// Maps: Business Type → Services/Specialties for that business type
export const servicesByBusinessType: Record<string, string[]> = {
  // Digital Marketing Agencies
  'Digital Marketing Agency': ['Social Media Management', 'Content Strategy', 'Analytics & Reporting', 'Campaign Management', 'SEO Optimization', 'PPC Management'],
  'Marketing Consulting Firm': ['Brand Strategy', 'Growth Strategy', 'Market Research', 'Competitive Analysis', 'Campaign Management', 'Performance Metrics'],
  'SEO Services Company': ['SEO Optimization', 'Keyword Research', 'Technical SEO', 'Link Building', 'Content Strategy', 'Local SEO'],
  'Social Media Marketing Agency': ['Social Media Management', 'Content Creation', 'Community Management', 'Influencer Outreach', 'Campaign Management', 'Analytics & Reporting'],
  'Content Marketing Agency': ['Content Strategy', 'Content Creation', 'Blog Posts', 'Social Posts', 'Video Scripts', 'Content Curation'],
  'Growth Hacking Firm': ['Growth Strategy', 'User Acquisition', 'Conversion Optimization', 'Experimentation', 'Analytics & Reporting', 'Product Development'],
  'Marketing Automation Specialist': ['Automation Setup', 'Workflow Design', 'Integration Services', 'Email Campaign Management', 'List Building', 'A/B Testing'],

  // Brand Ambassador & Influencer Management
  'Influencer Management Agency': ['Product Endorsement', 'Sponsored Posts', 'Campaign Participation', 'Content Creation', 'Influencer Outreach', 'Brand Advocacy'],
  'Brand Ambassador Network': ['Event Representation', 'Social Media Promotion', 'Product Sampling', 'Community Engagement', 'Brand Representation', 'Promotional Engagement'],
  'Community Management Company': ['Community Management', 'Engagement Strategy', 'Moderation', 'Content Curation', 'Community Development', 'Feedback Collection'],
  'Talent Representation Agency': ['Artist Management', 'Contract Negotiation', 'Career Development', 'Talent Booking', 'Partnership Development', 'Network Building'],
  'Promotional Services Company': ['Event Promotion', 'Promotional Engagement', 'Brand Activation', 'Interactive Experience', 'Campaign Participation', 'Trade Show Appearances'],

  // Media & Communications
  'PR and Communications Firm': ['Media Relations', 'Press Release Writing', 'Communications Strategy', 'Event Promotion', 'Crisis Management', 'Brand Reputation'],
  'Media Relations Agency': ['Media Relations', 'Press Kit Preparation', 'Media Outreach', 'Media Briefings', 'Journalist Relations', 'Coverage Monitoring'],
  'Public Relations Company': ['Press Release Writing', 'Media Relations', 'Event Promotion', 'Crisis Management', 'Brand Positioning', 'Statement Preparation'],
  'Communications Consulting': ['Communications Strategy', 'Internal Communications', 'External Communications', 'Messaging Strategy', 'Content Distribution', 'Brand Voice'],

  // Media Production
  'Production Company': ['Production Management', 'Crew Coordination', 'Budget Management', 'Post-Production Supervision', 'Creative Direction', 'Location Coordination'],
  'Video Production House': ['Video Filming', 'Video Editing', 'Motion Graphics', 'Color Correction', 'Live Streaming', 'Production Management'],
  'Media Production Studio': ['Production Management', 'Creative Direction', 'Crew Coordination', 'Post-Production Supervision', 'Technical Setup', 'Equipment Management'],
  'Broadcasting Company': ['Live Production', 'Broadcast Management', 'Technical Setup', 'Equipment Maintenance', 'Live Broadcasting', 'Contingency Planning'],
  'Broadcast Services Company': ['Live Production', 'Technical Setup', 'Broadcast Management', 'Equipment Setup', 'Quality Assurance', 'Technical Support'],

  // Design & Art
  'Design Agency': ['Logo Design', 'Brand Design', 'Digital Design', 'Print Design', 'Visual Design', 'Design Strategy'],
  'Creative Design Studio': ['Graphic Design', 'UI/UX Design', 'Illustration', 'Motion Design', 'Visual Design', 'Brand Identity'],
  'Graphic Design Studio': ['Logo Design', 'Print Design', 'Digital Design', 'Brand Identity', 'Graphics', 'Design Consultation'],
  'Branding and Design Firm': ['Brand Strategy', 'Logo Design', 'Brand Guidelines', 'Brand Identity', 'Design Strategy', 'Visual Design'],
  'Digital Design Company': ['UI Design', 'Digital Design', 'Web Design', 'App Design', 'Motion Graphics', 'Interactive Design'],
  'Design Consulting Firm': ['Design Consulting', 'Design Strategy', 'Design Audit', 'Custom Solutions', 'Brand Design', 'Design Direction'],

  // Modelling & Talent
  'Modeling Agency': ['Portfolio Building', 'Commercial Modeling', 'Fashion Modeling', 'Runway Shows', 'Casting Management', 'Talent Development'],
  'Talent Agency': ['Talent Booking', 'Contract Negotiation', 'Portfolio Building', 'Career Development', 'Network Building', 'Partnership Development'],
  'Model Management Company': ['Portfolio Building', 'Booking Management', 'Career Development', 'Talent Development', 'Contract Negotiation', 'Casting'],
  'Casting Agency': ['Casting Services', 'Talent Selection', 'Booking Management', 'Contract Negotiation', 'Talent Database', 'Audition Coordination'],
  'Talent Representation Firm': ['Talent Management', 'Contract Negotiation', 'Career Development', 'Network Building', 'Booking Management', 'Partnership Development'],

  // Dance & Choreography
  'Dance Studio': ['Dance Classes', 'Private Lessons', 'Group Training', 'Online Instruction', 'Performance Production', 'Rehearsal Coordination'],
  'Choreography Company': ['Choreography Creation', 'Dance Direction', 'Movement Training', 'Concept Development', 'Performance Coordination', 'Artistic Direction'],
  'Dance Production Team': ['Choreography Creation', 'Dance Direction', 'Performer Coordination', 'Production Management', 'Creative Direction', 'Performance Oversight'],
  'Performance Group': ['Live Performance', 'Choreography Interpretation', 'Concert Performances', 'Event Performance', 'Touring', 'Artistic Direction'],
  'Dance and Movement Company': ['Choreography Creation', 'Movement Training', 'Dance Direction', 'Performance Production', 'Concept Development', 'Artistic Direction'],

  // Acting & Theater
  'Casting Agency': ['Casting Services', 'Talent Selection', 'Audition Coordination', 'Contract Negotiation', 'Talent Database', 'Booking Management'],
  'Talent Agency': ['Talent Booking', 'Contract Negotiation', 'Career Development', 'Portfolio Building', 'Network Building', 'Partnership Development'],
  'Acting Studio': ['Acting Classes', 'Private Coaching', 'Performance Training', 'Scene Work', 'Character Development', 'Audition Preparation'],
  'Theater Company': ['Live Performance', 'Stage Acting', 'Production Management', 'Direction Services', 'Rehearsal Coordination', 'Performer Coordination'],
  'Entertainment Management Firm': ['Artist Management', 'Contract Negotiation', 'Career Development', 'Network Building', 'Partnership Development', 'Talent Booking'],

  // Film & Video Production
  'Film Production Company': ['Film Direction', 'Production Planning', 'Crew Management', 'Budget Management', 'Post-Production', 'Creative Oversight'],
  'Production Studio': ['Production Management', 'Creative Direction', 'Crew Coordination', 'Technical Setup', 'Post-Production Supervision', 'Equipment Management'],
  'Digital Production Company': ['Video Production', 'Digital Content Creation', 'Animation', 'Motion Graphics', 'Visual Effects', 'Post-Production'],
  'Independent Production Company': ['Film Production', 'Creative Control', 'Budget Management', 'Crew Coordination', 'Post-Production', 'Distribution Support'],
  'Film and Video Services': ['Film Production', 'Video Production', 'Production Management', 'Technical Services', 'Post-Production', 'Equipment Rental'],

  // Audio Production
  'Recording Studio': ['Audio Recording', 'Mixing', 'Mastering', 'Session Management', 'Equipment Setup', 'Quality Control'],
  'Audio Production Studio': ['Audio Recording', 'Audio Mixing', 'Sound Design', 'Audio Effects', 'Mastering', 'Audio Restoration'],
  'Sound Design Company': ['Sound Design', 'Audio Effects', 'Ambient Design', 'Sonic Branding', 'Sound Design', 'Audio Production'],
  'Music Production Studio': ['Music Production', 'Audio Recording', 'Mixing', 'Mastering', 'Beat Production', 'Song Production'],
  'Mastering Studio': ['Audio Mastering', 'Mastering Engineer', 'Format Conversion', 'Distribution Prep', 'Quality Assurance', 'Final Optimization'],
  'Audio Engineering Firm': ['Audio Recording', 'Mixing', 'Mastering', 'Audio Restoration', 'Sound Design', 'Technical Consulting'],

  // Music
  'Record Label': ['Music Production', 'Artist Promotion', 'Distribution', 'Royalty Management', 'A&R Services', 'Album Production'],
  'Music Production Company': ['Music Production', 'Beat Production', 'Song Production', 'Album Production', 'Audio Recording', 'Mixing'],
  'Music Management Firm': ['Artist Management', 'Contract Negotiation', 'Career Development', 'Network Building', 'Partnership Development', 'Booking Management'],
  'Music Publishing Company': ['Music Publishing', 'Royalty Management', 'Rights Management', 'Distribution', 'Licensing', 'Catalog Management'],

  // Event Management
  'Event Management Company': ['Event Planning', 'Logistics Management', 'Vendor Coordination', 'On-site Management', 'Full Event Planning', 'Creative Concept'],
  'Event Planning Agency': ['Event Planning', 'Timeline Management', 'Vendor Coordination', 'Budget Planning', 'Logistics Management', 'Implementation'],
  'Conference and Event Organizer': ['Event Planning', 'Conference Organization', 'Logistics Management', 'Vendor Coordination', 'Registration Management', 'Technical Setup'],
  'Event Production Company': ['Event Production', 'Creative Concept', 'Technical Execution', 'Crew Coordination', 'On-site Management', 'Quality Assurance'],
  'Venue and Event Services': ['Space Management', 'Facility Management', 'Technical Support', 'Event Coordination', 'Logistics Support', 'On-site Management'],

  // Photography
  'Photography Studio': ['Studio Photography', 'Portrait Photography', 'Commercial Photography', 'Product Photography', 'Event Photography', 'Photo Editing'],
  'Photography Agency': ['Photography Services', 'Photographer Booking', 'Commercial Photography', 'Product Photography', 'Event Coverage', 'Portfolio Building'],
  'Commercial Photography Company': ['Commercial Photography', 'Product Photography', 'Corporate Photography', 'Advertising Photography', 'E-commerce Photography', 'Photo Editing'],
  'Photo Production House': ['Photography', 'Photo Editing', 'Retouching', 'Color Correction', 'Image Curation', 'Batch Processing'],
  'Professional Photography Services': ['Photography', 'Photo Editing', 'Retouching', 'Color Correction', 'Image Enhancement', 'Portfolio Building'],

  // Design
  'Design Studio': ['Logo Design', 'Brand Design', 'Digital Design', 'Print Design', 'Visual Design', 'Design Strategy'],
  'Creative Services Company': ['Graphic Design', 'Design Consulting', 'Brand Design', 'Creative Direction', 'Design Strategy', 'Custom Solutions'],
  'Multi-discipline Design Studio': ['Graphic Design', 'UI/UX Design', 'Illustration', 'Motion Design', 'Brand Identity', 'Design Consultation'],

  // Missing Services - Added to complete cascading dropdowns
  'Relationship Management': ['Account Management Services', 'Strategic Partner Management', 'Client Retention & Loyalty Programs', 'VIP Relationship Coordination', 'Stakeholder Engagement Services', 'Account Growth Strategy', 'Client Support & Advocacy', 'Relationship Health Monitoring'],
  'Audience Management': ['Audience Segmentation & Analytics', 'Community Member Management', 'Audience Growth Strategy', 'Engagement Performance Tracking', 'Member Retention Programs', 'Audience Feedback Coordination', 'Community Engagement Planning', 'Audience Behavior Analysis'],
  'Feedback Analysis': ['Customer Feedback Collection & Analysis', 'Survey Data Analysis Report', 'Sentiment & Social Listening Analysis', 'User Experience Feedback Research', 'Focus Group Moderation & Insights', 'Competitive Feedback Analysis', 'Actionable Insights Report', 'Trend & Pattern Identification'],
  'Media Coordination': ['Media Planning & Scheduling', 'Press Release Distribution', 'Media Outreach & Pitching', 'Interview Coordination & Logistics', 'Media Kit Development & Distribution', 'Press Conference Planning & Management', 'Journalist Relations Management', 'Media Event Coordination'],
  'Brand Representation': ['On-Site Brand Ambassador Services', 'Event Activation & Brand Presence', 'Product Demonstration & Sampling', 'Brand Spokesperson & Voice Services', 'Digital Campaign Representation', 'Promotional Event Appearances', 'Trade Show & Exhibition Support', 'Brand Experience Coordination'],
};

export const currencies = ['UGX', 'USD', 'EUR', 'GBP'];
